"use client"

import { useState } from "react"
import { FileText, Download, Leaf, Calendar, Sparkles, UploadCloud, ChevronRight } from "lucide-react"
import Link from "next/link"
import type { AiAnalysis } from "@/lib/supabase/types"

type Filter = "all" | "this_month" | "last_month"

function isThisMonth(dateStr: string) {
  const d = new Date(dateStr)
  const now = new Date()
  return d.getFullYear() === now.getFullYear() && d.getMonth() === now.getMonth()
}

function isLastMonth(dateStr: string) {
  const d = new Date(dateStr)
  const now = new Date()
  const last = new Date(now.getFullYear(), now.getMonth() - 1, 1)
  return d.getFullYear() === last.getFullYear() && d.getMonth() === last.getMonth()
}

function formatCo2(grams: number | null) {
  if (grams == null) return "—"
  return grams >= 1000 ? `${(grams / 1000).toFixed(2)} kg CO₂` : `${grams.toFixed(0)} g CO₂`
}

function downloadReport(analysis: AiAnalysis) {
  const recs = (analysis.recommendations as string[]).map((r, i) => `  ${i + 1}. ${r}`).join("\n")
  const text = [
    "═══════════════════════════════════════",
    "  InvisibleWatts — Digital Carbon Report",
    "═══════════════════════════════════════",
    "",
    `Generated: ${new Date(analysis.created_at).toLocaleString()}`,
    `Entries analysed: ${analysis.entry_count}`,
    `CO₂ estimate: ${formatCo2(analysis.co2_estimate_grams)}`,
    "",
    "── Summary ─────────────────────────────",
    analysis.summary,
    "",
    "── Recommendations ──────────────────────",
    recs,
    "",
    "═══════════════════════════════════════",
    "InvisibleWatts — invisiblewatts.vercel.app",
  ].join("\n")

  const blob = new Blob([text], { type: "text/plain" })
  const url = URL.createObjectURL(blob)
  const a = document.createElement("a")
  a.href = url
  a.download = `iw-report-${analysis.created_at.slice(0, 10)}.txt`
  a.click()
  URL.revokeObjectURL(url)
}

export default function ReportsContent({
  analyses,
  entriesTotal,
}: {
  analyses: AiAnalysis[]
  entriesTotal: number
}) {
  const [filter, setFilter] = useState<Filter>("all")

  const filtered = analyses.filter((a) => {
    if (filter === "this_month") return isThisMonth(a.created_at)
    if (filter === "last_month") return isLastMonth(a.created_at)
    return true
  })

  const totalCo2 = analyses.reduce((s, a) => s + (a.co2_estimate_grams ?? 0), 0)

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex items-start justify-between flex-wrap gap-4">
        <div>
          <h1 className="text-3xl font-bold text-gray-900 dark:text-white mb-2">Reports</h1>
          <p className="text-gray-600 dark:text-gray-400">
            Your digital carbon footprint reports generated by AI
          </p>
        </div>
        <Link
          href="/upload"
          className="flex items-center gap-2 px-4 py-2 rounded-lg bg-gradient-to-r from-blue-500 to-cyan-500 hover:from-blue-600 hover:to-cyan-600 text-white text-sm font-semibold transition-all"
        >
          <UploadCloud className="w-4 h-4" />
          New Report
        </Link>
      </div>

      {/* Stats row — only show if data exists */}
      {analyses.length > 0 && (
        <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
          <div className="bg-white dark:bg-[#0F0F12] rounded-xl p-4 border border-gray-200 dark:border-[#1F1F23]">
            <p className="text-xs text-gray-500 dark:text-gray-400 mb-1">Total Reports</p>
            <p className="text-2xl font-bold text-gray-900 dark:text-white">{analyses.length}</p>
          </div>
          <div className="bg-white dark:bg-[#0F0F12] rounded-xl p-4 border border-gray-200 dark:border-[#1F1F23]">
            <p className="text-xs text-gray-500 dark:text-gray-400 mb-1">Entries Analysed</p>
            <p className="text-2xl font-bold text-gray-900 dark:text-white">{entriesTotal}</p>
          </div>
          <div className="bg-white dark:bg-[#0F0F12] rounded-xl p-4 border border-gray-200 dark:border-[#1F1F23]">
            <p className="text-xs text-gray-500 dark:text-gray-400 mb-1">Total CO₂ Tracked</p>
            <p className="text-2xl font-bold text-gray-900 dark:text-white">{formatCo2(totalCo2)}</p>
          </div>
        </div>
      )}

      {/* Filter tabs */}
      <div className="flex gap-2 flex-wrap">
        {(["all", "this_month", "last_month"] as Filter[]).map((f) => (
          <button
            key={f}
            onClick={() => setFilter(f)}
            className={`px-4 py-2 rounded-lg text-sm font-medium transition-colors ${
              filter === f
                ? "bg-blue-500 text-white"
                : "bg-white dark:bg-[#0F0F12] text-gray-700 dark:text-gray-300 border border-gray-200 dark:border-[#1F1F23] hover:bg-gray-50 dark:hover:bg-[#1F1F23]"
            }`}
          >
            {f === "all" ? "All Reports" : f === "this_month" ? "This Month" : "Last Month"}
          </button>
        ))}
      </div>

      {/* Empty state */}
      {analyses.length === 0 ? (
        <div className="flex flex-col items-center justify-center py-24 gap-4 text-center">
          <div className="p-4 rounded-full bg-gray-100 dark:bg-[#1F1F23]">
            <FileText className="w-8 h-8 text-gray-400 dark:text-gray-500" />
          </div>
          <div>
            <h2 className="text-lg font-semibold text-gray-900 dark:text-white mb-1">No reports yet</h2>
            <p className="text-sm text-gray-500 dark:text-gray-400 max-w-xs">
              Upload your device usage data and run an AI analysis to generate your first digital carbon report.
            </p>
          </div>
          <Link
            href="/upload"
            className="flex items-center gap-2 px-5 py-2.5 rounded-lg bg-gradient-to-r from-blue-500 to-cyan-500 hover:from-blue-600 hover:to-cyan-600 text-white text-sm font-semibold transition-all"
          >
            <UploadCloud className="w-4 h-4" />
            Upload Usage Data
          </Link>
        </div>
      ) : filtered.length === 0 ? (
        <div className="py-16 text-center text-gray-500 dark:text-gray-400 text-sm">
          No reports for this period.
        </div>
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          {filtered.map((analysis) => (
            <ReportCard key={analysis.id} analysis={analysis} />
          ))}
        </div>
      )}

      {/* Generate new report CTA */}
      {analyses.length > 0 && (
        <div className="bg-gradient-to-br from-blue-50 to-cyan-50 dark:from-[#1F1F23] dark:to-[#0F0F12] rounded-xl p-6 border border-blue-200 dark:border-[#2B2B30]">
          <div className="flex items-start justify-between gap-4">
            <div>
              <h3 className="text-base font-semibold text-gray-900 dark:text-white mb-1">
                Generate a new report
              </h3>
              <p className="text-sm text-gray-600 dark:text-gray-400">
                Upload new device usage data and run AI analysis to add another report.
              </p>
            </div>
            <Link
              href="/upload"
              className="flex-shrink-0 flex items-center gap-2 px-4 py-2 rounded-lg bg-blue-500 hover:bg-blue-600 text-white text-sm font-medium transition-colors"
            >
              <Sparkles className="w-4 h-4" />
              Analyse
            </Link>
          </div>
        </div>
      )}
    </div>
  )
}

function ReportCard({ analysis }: { analysis: AiAnalysis }) {
  const recs = analysis.recommendations as string[]
  const date = new Date(analysis.created_at)

  return (
    <div className="bg-white dark:bg-[#0F0F12] rounded-xl border border-gray-200 dark:border-[#1F1F23] hover:shadow-lg transition-shadow overflow-hidden">
      {/* Card header */}
      <div className="flex items-start justify-between p-5 pb-4">
        <div className="flex items-start gap-3">
          <div className="p-2 bg-green-100 dark:bg-green-900/30 rounded-lg flex-shrink-0">
            <Leaf className="w-5 h-5 text-green-600 dark:text-green-400" />
          </div>
          <div>
            <h3 className="text-sm font-semibold text-gray-900 dark:text-white leading-tight">
              Digital Carbon Report
            </h3>
            <div className="flex items-center gap-1 text-xs text-gray-500 dark:text-gray-400 mt-0.5">
              <Calendar className="w-3 h-3" />
              {date.toLocaleDateString("en-US", { month: "short", day: "numeric", year: "numeric" })}
            </div>
          </div>
        </div>
        <button
          onClick={() => downloadReport(analysis)}
          title="Download as text"
          className="p-2 hover:bg-gray-100 dark:hover:bg-[#1F1F23] rounded-lg transition-colors flex-shrink-0"
        >
          <Download className="w-4 h-4 text-gray-500 dark:text-gray-400" />
        </button>
      </div>

      {/* Stats row */}
      <div className="flex gap-4 px-5 pb-4 border-b border-gray-100 dark:border-[#1F1F23]">
        <div>
          <p className="text-xs text-gray-400 mb-0.5">CO₂ estimate</p>
          <p className="text-lg font-bold text-gray-900 dark:text-white">
            {formatCo2(analysis.co2_estimate_grams)}
          </p>
        </div>
        <div className="border-l border-gray-100 dark:border-[#1F1F23] pl-4">
          <p className="text-xs text-gray-400 mb-0.5">Entries</p>
          <p className="text-lg font-bold text-gray-900 dark:text-white">{analysis.entry_count}</p>
        </div>
      </div>

      {/* Summary */}
      <div className="px-5 py-4 border-b border-gray-100 dark:border-[#1F1F23]">
        <p className="text-xs text-gray-500 dark:text-gray-400 font-medium uppercase mb-1.5">Summary</p>
        <p className="text-sm text-gray-700 dark:text-gray-300 leading-relaxed line-clamp-3">
          {analysis.summary}
        </p>
      </div>

      {/* Top recommendations */}
      {recs.length > 0 && (
        <div className="px-5 py-4">
          <p className="text-xs text-gray-500 dark:text-gray-400 font-medium uppercase mb-2">
            Top Recommendations
          </p>
          <div className="space-y-1.5">
            {recs.slice(0, 3).map((rec, i) => (
              <div key={i} className="flex items-start gap-2 text-sm text-gray-700 dark:text-gray-300">
                <div className="w-1.5 h-1.5 rounded-full bg-blue-500 flex-shrink-0 mt-1.5" />
                <span className="line-clamp-2">{rec}</span>
              </div>
            ))}
            {recs.length > 3 && (
              <p className="text-xs text-blue-500 dark:text-blue-400 pl-3.5">
                +{recs.length - 3} more in AI Insights
              </p>
            )}
          </div>
        </div>
      )}
    </div>
  )
}
